name: Jenkins Integration

on:
  pull_request:
  push:
    branches: 
      - main
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins
      uses: actions/jenkins-cli-action@v1
      with:
        jenkins-url: ${{ JENKINS_URL }}
        jenkins-user: ${{ JENKINS_USERNAME }}
        jenkins-pass: ${{ JENKINS_PASSWORD }}
        command: build job/statuschecks -p git-branch=${{ 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 }}
