# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.name: Multi-Branch Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

    - name: Setup Node
      run: |
        apt-get install -y nodejs
        node -v
        npm -v

    - name: Install dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build
        
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        with:
          ref: ${{ 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 }}

    - name: Setup Node
      run: |
        apt-get install -y nodejs
        node -v
        npm -v

    - name: Install dependencies
      run: |
        npm install

    - name: Test
      run: |
        npm run test
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        with:
          ref: ${{ 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 }}

    - name: Deploy
      run: |
        curl -X POST http://your-jenkins-server/job/your-job-name/buildWithParameters --data token=your-token --data branch=${{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 }}
